In [1]:
import numpy as np

In [7]:
A=np.ones((2,1))
print A

[[ 1.]
 [ 1.]]


In [10]:
??A

In [12]:
np.ones??

In [13]:
np.shape(A)

(2, 1)

In [20]:
A.shape[1]

1

In [21]:
A.size

2

In [22]:
B=np.array([[1,2,3],[4,5,6]])

In [23]:
B.shape

(2, 3)

In [24]:
B.size

6

In [25]:
B.ndim

2

In [26]:
C=np.array([7,8,9])

In [28]:
print B

[[1 2 3]
 [4 5 6]]


In [29]:
print C

[7 8 9]


In [31]:
D= np.array([B,C])

In [32]:
print D

[array([[1, 2, 3],
       [4, 5, 6]]) array([7, 8, 9])]


In [33]:
D.shape

(2,)

In [35]:
D=np.vstack([B,C])
print D

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [36]:
D.shape

(3, 3)

In [38]:
D[1,:]

array([4, 5, 6])

In [39]:
D[1:3,:]

array([[4, 5, 6],
       [7, 8, 9]])

In [44]:
D[1:D.shape[0],:]

array([[4, 5, 6],
       [7, 8, 9]])

In [49]:
D[-2:,:]

array([[4, 5, 6],
       [7, 8, 9]])

In [50]:
E=D>5
print E

[[False False False]
 [False False  True]
 [ True  True  True]]


In [51]:
E.astype(int)

array([[0, 0, 0],
       [0, 0, 1],
       [1, 1, 1]])

In [57]:
X=np.nonzero(D>3)

In [53]:
print D

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [59]:
X

(array([1, 1, 1, 2, 2, 2]), array([0, 1, 2, 0, 1, 2]))

In [60]:
X??

In [61]:
D[X]

array([4, 5, 6, 7, 8, 9])

In [62]:
D[D>4]

array([5, 6, 7, 8, 9])

In [64]:
7*np.ones((2,2))

array([[ 7.,  7.],
       [ 7.,  7.]])