In [1]:
%matplotlib inline
import numpy as np 
import matplotlib.pyplot as plt

In [2]:
def sigmoid(x):
    return (1/(1+np.exp(-x)));

def get_weights(cur_layer,next_layer):
    """ Returns random weights to start with. including last row (all ones) for bias
    where cur_layer is no of neurons for current layer and
    next_layer is no of neurons for next layer"""
    z=np.random.random((cur_layer-1,next_layer));
    b=np.ones((1,next_layer));
    w=np.vstack((z,b));
    return w;

def perceptron(input_x,weights):
    return sigmoid(np.dot(input_x,weights));

def step(x):
    return 1*(x>0);

def normal_perc(x,w,b):
    return  step(np.dot(x,w)+b);    

In [3]:
## Excersie to find weights of hidden layer 2 for 4 output neurons
# http://neuralnetworksanddeeplearning.com/chap1.html#exercise_513527 

In [4]:
weights= np.array(([0,0,0,0],[1,0,0,0],[0,1,0,0],[1,1,0,0],[0,0,1,0],[1,0,1,0],[0,1,1,0],[1,1,1,0],[0,0,0,1],[1,0,0,1]));

In [5]:
print(weights)

[[0 0 0 0]
 [1 0 0 0]
 [0 1 0 0]
 [1 1 0 0]
 [0 0 1 0]
 [1 0 1 0]
 [0 1 1 0]
 [1 1 1 0]
 [0 0 0 1]
 [1 0 0 1]]


In [6]:
input_x=0.01*np.ones((1,10))

In [7]:
print(input_x)

[[ 0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01]]


In [8]:
# **finding if the weights currectly recognises digit 4**
input_x[0,4]=0.01;
input_x[0,5]=0.99;
print(input_x)

[[ 0.01  0.01  0.01  0.01  0.01  0.99  0.01  0.01  0.01  0.01]]


In [9]:
output_array=np.dot(input_x,weights)
print(output_array)

[[ 1.03  0.04  1.02  0.02]]


In [10]:
print(normal_perc(input_x,weights,-0.8))

[[1 0 1 0]]
